services:
  stick-it-server:
    container_name: stick-it-server
    build: .
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      EMAIL: lr.dev.projects@gmail.com

      # ---- Edit to change default: ----
      # PORT: 8081

      # ---- From .env file: -------
      # POSTGRES_PASSWORD
      # POSTGRES_USER
      # POSTGRES_DB
      # EMAIL_PASSWORD
      # SECRET
    depends_on:
      - db
    networks:
      - net
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: stick-it-db
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - net

networks:
  net:
    name: "stick-it-network"