services:
  stick-it-server:
    image: lrprojects/stick-it-server:latest
    restart: unless-stopped
    ports:
      - ${PORT}:8080
    env_file:
      - ./.env
    depends_on:
      - db
      - minio

  db:
    image: postgis/postgis:17-master
    restart: unless-stopped
    container_name: stick-it-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backup:/backup
      - ./init:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio
    container_name: minio_local
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: admin
    restart: unless-stopped
    command: server /data --console-address ":9001"

  # influx ...
