services:
  stick-it-server:
    image: lrprojects/stick-it-server:latest
    restart: unless-stopped
    ports:
      - ${PORT}:8081
    env_file:
      - ./.env
    depends_on:
      - db
      - minio

  db:
    image: postgis/postgis:16-master
    restart: unless-stopped
    container_name: stick-it-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/manual/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  minio:
    image: minio/minio
    container_name: minio_local
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    environment:
      MINIO_DOMAIN: ${MINIO_ENDPOINT}
    restart: unless-stopped
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"

  # influx ...
