services:
  stick-it-server:
    container_name: lrprojects/stick-it-server:<VERSION>
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - ./.env
    environment:
      DB_URL: jdbc:postgresql://db:5432/sticker
    depends_on:
      - db
    networks:
      - net
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: stick-it-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backup:/backup
    env_file:
      - ./.env
    networks:
      - net

networks:
  net:
    name: "stick-it-network"