services:
  stick-it-server:
    container_name: lrprojects/stick-it-server:<VERSION>
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - ./.env
    environment:
      DB_URL: jdbc:postgresql://db:5432/sticker
    depends_on:
      - db
    networks:
      - net
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: stick-it-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backup:/backup

    networks:
      - net
  redis:
    image: redis:8.0-M02
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    networks:
      - net
  minio:
    image: minio/minio
    container_name: minio_local
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    environment:
      MINIO_DOMAIN: ${MINIO_ENDPOINT}
    restart: unless-stopped
    command: server /data --console-address ":9001"


networks:
  net:
    name: "stick-it-network"