services:
  stick-it-server:
    container_name: lrprojects/stick-it-server:<VERSION>
    restart: unless-stopped
    ports:
      - ${PORT}:8081
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - minio
    networks:
      - net
  db:
    image: postgis/postgis:16-master
    restart: unless-stopped
    container_name: stick-it-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/manual/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - net
  redis:
    image: redis:8.0-M02
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - ./.env
    networks:
      - net
  minio:
    image: minio/minio
    container_name: minio_local
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    environment:
      MINIO_DOMAIN: ${MINIO_ENDPOINT}
    restart: unless-stopped
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"

networks:
  net:
    name: "stick-it-network"