email:
  from: lr.dev.projects@gmail.com
logging:
  file:
    name: ./logs/server.log
server:
  port: 8081
  servlet:
    context-path: /
    session:
      persistent: false
  forward-headers-strategy: native
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    active: secrets
  datasource:
    url: jdbc:postgresql://localhost:5432/export_20_8
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true
    baseline-version: 0.0.1
    clean-disabled: false

springdoc:
  swagger-ui:
    path: /api-docs
