mail:
  from: ${MAIL_FROM}
  host: ${MAIL_HOST}
  password: ${MAIL_PASSWORD}
  port: ${MAIL_PORT}
  protocol: ${MAIL_PROTOCOL}


server:
  port: ${PORT:8081}
  servlet:
    context-path: /
    session:
      persistent: false
  forward-headers-strategy: native
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
spring:
  config:
    import: optional:file:.env[.properties]
  security:
   filter:
     order: 10
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0.0.1
    clean-disabled: false

springdoc:
  api-docs:
    path: /public/api-docs
  swagger-ui:
    path: /public/swagger-ui.html
token:
  access-token-exploration: 900         # 15 min
  refresh-token-exploration: 31556952   # 1 year
  secret: ${SECRET}
app:
  url: ${APP_URL}