server:
  port: ${PORT:8081}
  servlet:
    context-path: /
    session:
      persistent: false
  forward-headers-strategy: native
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /public/**
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0.0.1
    clean-disabled: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false

management:
  influx:
    metrics:
      export:
        bucket: ${INFLUX_BUCKET}
        org: ${INFLUX_ORG}
        token: ${INFLUX_TOKEN}
        uri: ${INFLUX_URL}
        enabled: ${INFLUX_ENABLED:false}




springdoc:
  api-docs:
    path: /public/api-docs
  swagger-ui:
    path: /public/swagger-ui.html

app:
  mail:
    from: ${MAIL_FROM}
    host: ${MAIL_HOST}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PROTOCOL}
    batchSize: ${MAIL_BATCH_SIZE:25}
    batchDuration: ${MAIL_BATCH_DURATION:60}
  config:
    url: ${APP_URL}
    maxLoginAttempts: ${MAX_LOGIN_ATTEMPTS:10}
    firebase-config-path: ${FIREBASE_CONFIG_PATH}
  token:
    access-token-exploration: ${ACCESS_TOKEN_EXPIRATION:900}  # 15 min
    refresh-token-exploration: ${REFRESH_TOKEN_EXPIRATION:31556952}   # 1 year
    admin-account-name: ${ADMIN_ACCOUNT_NAME}
  minio:
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    endpoint: ${MINIO_ENDPOINT}
    bucket-name: ${MINIO_BUCKET}
  achievements:
    mona-group-id: ${ACHIEVEMENT_MONA_GROUP_ID:d9631336-5c32-4f64-83a7-7a4fcdae4dd6}
    created-before: ${ACHIEVEMENT_CREATED_BEFORE:2023-12-10T02:43:44.402768+00:00}