email:
  from: ${EMAIL}
  psw: ${EMAIL_PSW}
logging:
  file:
    name: ./logs/server.log
server:
  port: ${PORT:8081}
  servlet:
    context-path: /
    session:
      persistent: false
  forward-headers-strategy: native
  error:
    whitelabel:
      enabled: false
spring:
  security:
   filter:
     order: 10
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/export_2_8
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0.0.1
    clean-disabled: false
springdoc:
  api-docs:
    path: /public/api-docs
  swagger-ui:
    path: /public/swagger-ui.html
  enable-kotlin: false