mail:
  from: ${MAIL_FROM}
  host: ${MAIL_HOST}
  password: ${MAIL_PASSWORD}
  port: ${MAIL_PORT}
  protocol: ${MAIL_PROTOCOL}


server:
  port: ${PORT:8081}
  servlet:
    context-path: /
    session:
      persistent: false
  forward-headers-strategy: native
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /public/**
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0.0.1
    clean-disabled: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false

springdoc:
  api-docs:
    path: /public/api-docs
  swagger-ui:
    path: /public/swagger-ui.html
token:
  access-token-exploration: 900         # 15 min
  refresh-token-exploration: 91556952   # 3 year
  admin-account-name: ${ADMIN_ACCOUNT_NAME}
app:
  url: ${APP_URL}
  maxLoginAttempts: 10
minio:
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  endpoint: ${MINIO_ENDPOINT}
  bucket-name: ${MINIO_BUCKET}