# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: MonaServer

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAIL_PSW: ${{ secrets.MAIL_PSW }}
        AUTH_TOKEN_ADMIN: ${{ secrets.AUTH_TOKEN_ADMIN }}
        DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        PORT: ${{ secrets.PORT }}
        SECRET: ${{ secrets.SECRET }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: target/MonaServer-2.jar
        
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/MonaServer-2.jar
        remote: target/MonaServer-2.jar
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: sudo systemctl restart server
