name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(xmlstarlet sel -t -v "/_:project/_:version" pom.xml)
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Create settings.xml for GitHub Packages authentication
        run: |
          echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd'>" > ~/.m2/settings.xml
          echo "<servers><server><id>github</id><username>lr101</username><password>${{ secrets.GH_TOKEN }}</password></server></servers>" >> ~/.m2/settings.xml
          echo "</settings>" >> ~/.m2/settings.xml

      - name: Build Docker image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=lrprojects/stick-it-server:${{ steps.extract_version.outputs.version }} --settings ~/.m2/settings.xml
        # Replace "my-spring-boot-app" with your desired image name

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tag Docker image with :latest
        run: docker tag lrprojects/stick-it-server:${{ steps.extract_version.outputs.version }} lrprojects/stick-it-server:latest


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Docker image to Docker Hub
        run: docker push lrprojects/stick-it-server:${{ steps.extract_version.outputs.version }}
