name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(xmlstarlet sel -t -v "/_:project/_:version" pom.xml)
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Build Docker image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=lrprojects/stick-it-server:${{ steps.extract_version.outputs.version }}
        # Replace "my-spring-boot-app" with your desired image name

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Docker image to Docker Hub
        run: docker push lrprojects/stick-it-server:${{ steps.extract_version.outputs.version }}
