name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(xmlstarlet sel -t -v "/_:project/_:version" pom.xml)
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: lrprojects/stick-it-server:${{ steps.extract_version.outputs.version }}
